### ISSUE TITLE
See also: My snippet that does similar thing in Vim/less

### ISSUE THREAD

**Issue by sunaku** [rhysd/tmux-edit#1]
https://sunaku.github.io/tmux-searchable-scrollback.html

``` sh
# search buffer (using less if Vim is not available)
bind-key -n M-/ capture-pane -S -32767 -J \; new-window ' \
  tmux save-buffer - \; delete-buffer | {                 \
    vim -R -c "set nofen is hls ic" -;                    \
    test $? -eq 127 && less;                              \
  };                                                      \
' \; send-keys G ? # go to bottom and search upward
```

**Comment by sunaku** [comment]
Oops, I misunderstood this plugin: it opens the contents of a buffer, not the pane contents, in an editor. :sweat_smile:

Sorry for the noise. :disappointed_relieved:  You might also consider exposing `tmux choose-buffer`, which lets the user select which buffer they want to edit (rather than always the most recent one, which is the case currently).

**Comment by rhysd** [comment]
Hi, thank you for the information.  Actually I'm a very beginner for tmux plugin and studying how it works now.  Your snippet looks useful as well :smiley:
